# Generated by Django 3.0.5 on 2020-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField()),
                ('y_id', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('d_id', models.IntegerField()),
                ('lec_no', models.IntegerField()),
            ],
        ),
    ]
