# Generated by Django 3.0.5 on 2020-11-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0004_auto_20201105_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('subject_id', models.IntegerField()),
                ('student_rolls', models.TextField()),
            ],
        ),
    ]
