# Generated by Django 3.0.5 on 2020-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.TextField()),
                ('t_email', models.TextField()),
                ('t_pwd', models.TextField()),
            ],
        ),
    ]
